apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: overleaf-service
  name: overleaf-service
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30060
  selector:
    io.kompose.service: overleaf-service
