apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: overleaf-service
  name: overleaf-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30060
  selector:
    io.kompose.service: overleaf-service
