apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: overleaf
  name: overleaf
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30055
  selector:
    io.kompose.service: overleaf
