apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: vim-adventures
  name: vim-adventures
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vim-adventures
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: vim-adventures
    spec:
      containers:
        - image: ghcr.io/therin/vima:latest
          name: vim-adventures
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home/node/vim-adventures/saved
              name: saved
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
        - name: saved
          persistentVolumeClaim:
            claimName: saved
      nodeSelector:
        kubernetes.io/hostname: k3d-main-server-0            
status: {}
