---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: re-notifier
  labels:
    app: re-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: re-notifier
  template:
    metadata:
      labels:
        app: re-notifier
      annotations:
        re-notifier.cfg: v1
    spec:
      containers:
        - name: re-notifier
          image: ghcr.io/therin/re-notifier:latest
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: telegram-bot-token
                  key: token
            - name: TELEGRAM_CHAT_IDS
              valueFrom:
                secretKeyRef:
                  name: telegram-chat-ids
                  key: chats
          volumeMounts:
            - name: re-database
              mountPath: /database
      imagePullSecrets:
      - name: regcred              
      volumes:
        - name: re-database
          persistentVolumeClaim:
            claimName: re-database
