---
apiVersion: v1
kind: Service
metadata:
  name: re-notifier
  labels:
    app: re-notifier
spec:
  type: NodePort
  selector:
    app: re-notifier
  ports:
    - name: "5900"
      port: 5900
      targetPort: 5900
      protocol: TCP
      nodePort: 30055
